### ISSUE TITLE
Center text vertically in a cell

### ISSUE THREAD

**Issue by ilbonte** [miachm/SODS#31]
Hi, first of all thanks for this tool :)

It looks like it's not possible to center a cell vertically.
In the picture the 2 cell are been centered using the libreoffice's tool

![image](https://user-images.githubusercontent.com/7412876/113359215-9c596f00-9347-11eb-93e6-a89e6db45a39.png)

Do you know how hard is to implement that? I'm might add this feature if I have time. Could you point me to the right portion of the code that I should modify?

**Comment by miachm** [comment]
Firstly, you need to have a simple ODS file which uses that.

Then, you need to unzip the ods file (yep, the ODS is in reality a zip file). Then, you should open the file content.xml in a XML Viewer (you can use Google Chrome if you don´t have one).

Then, you need to find what is the tag which defines the vertical align. Very likely, it´s "style:vertical-align".

Then, you need to add that functionality in the **Style** Class.

Then, you need to add that functionality in OdsReader class. So, when you are pasing a style, you can set the vertical-align. The name of the function is **readCellStyleEntry**

Then, you need to implement that functionaility in the OdsWritter class aswell.

Finally, you need to add an unit test in order to check if the behaviour is correct. For examply, you could write a file with vertical align and then open it again and see if the text is vertical-alightened.

It´s not really hard but a bit tedious if you are new in the library. You are free to work with it, otherwise, I might do it myself when I have extra time hehe :)

**Comment by miachm** [comment]
Implemented in v1.4.0
